version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    command: --port=3306 --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/Inscriptos_a_materias_SIU.xlsx:/app/Inscriptos_a_materias_SIU.xlsx:ro
      - ./backend/static/qr:/app/static/qr
    env_file: .env
    command: ["bash", "-c", "/app/esperar-mysql.sh db 3306 && flask run --host=0.0.0.0 --port=5000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: ["npm", "start"]

volumes:
  mysql_data:
  frontend_node_modules:
